/**
 * The 64-hexagram dataset, generated by reading
 *   docs/base_knowledge/64卦数据.json
 * at module-load time and re-keying it into the three lookup tables
 * the engine needs:
 *
 *   - HEXAGRAMS         (id 1..64 → HexagramMeta) for palatial lookups
 *   - HEXAGRAMS_BY_NAME (name → HexagramMeta)   for palaceSkill + LLM
 *   - HEXAGRAMS_BY_BITS (6-bit string → HexagramMeta) for hexagramSkill
 *
 * `64卦数据.json` is the canonical source (it carries the 卦辞, 爻辞,
 * symbol, type, shi, ying, and the upper/lower trigram names).
 *
 * ─────────────────────────────────────────────────────────────────────
 * Data file conventions (verified against 64卦数据.json and 排盘补充.md)
 * ─────────────────────────────────────────────────────────────────────
 *
 *   1. Each entry's `name` is the SHORT 卦名 ("乾", "否", "姤"); the
 *      `fullName` is the long form ("乾为天", "天地否", "天风姤"). We
 *      use `name` for HEXAGRAMS_BY_NAME since that's what the design
 *      doc and agent prompts use.
 *
 *   2. Each entry's `code` uses 2/1/0 where 2=阳 and 0=阴. The
 *      1-digit "1" never appears in the data. The engine's
 *      hexagramSkill, however, uses 1=阳 0=阴. We map 2→1 when
 *      building HEXAGRAMS_BY_BITS, and re-derive the same key from
 *      the trigram pair via bitsFromTrigrams() to keep a single
 *      source of truth.
 *
 *   3. Each entry's `type` field carries EITHER the 八宫 palaceType
 *      ("本宫" / "一世" / ... / "归魂") OR a decoration ("六冲" / "六合").
 *      The 1st entry of every 8-hexagram group is always the 本宫
 *      (sometimes tagged "六冲" if the upper==lower, e.g. 乾为天, 坤为地;
 *      sometimes tagged "六合" if the 6-bit code is the inverse of a
 *      六冲卦, e.g. 天地否 = 222111 = inverse of 地天泰 111222).
 *      We derive palaceType from the entry's INDEX WITHIN ITS GROUP
 *      (0=本宫, 1=一世, ..., 5=五世, 6=游魂, 7=归魂) — this is the
 *      single reliable rule.
 *
 *   4. The palace is the shared trigram of the 8-hexagram group.
 *      For 本宫 (e.g. 乾为天 = 乾/乾), the shared trigram is obvious
 *      (both upper and lower are 乾). For the rest, ONE of the two
 *      trigrams is the shared one — and we can identify it as the
 *      trigram that doesn't change as we walk the group.
 */
import dataJson from '../../../docs/base_knowledge/64卦数据.json';
import type { HexagramMeta } from '../types/chart';
import type { Palace, PalaceType, Trigram, WuXing } from '../types/basic';
import { TRIGRAM_ELEMENT } from './trigrams';
import { PALACE_OF_TRIGRAM, TRIGRAM_OF_PALACE } from './palaces';
import { bitsFromTrigrams } from './hexagrams';

interface RawHexagram {
  fullName: string;
  name: string;
  /** 八宫 palaceType OR a decoration (六冲/六合). We ignore this
   *  field and derive palaceType from index-in-group instead. */
  type: string;
  shangGua: Trigram;
  xiaGua: Trigram;
  shiYao: 1 | 2 | 3 | 4 | 5 | 6;
  yingYao: 1 | 2 | 3 | 4 | 5 | 6;
  symbol: string;
  /** 2=阳 0=阴. 1 never appears in the data. */
  code: string;
  guaCi: string;
  yaoCi: string[];
}

const RAW_DATA = dataJson as RawHexagram[];

const PALACE_TYPE_BY_INDEX: readonly PalaceType[] = [
  '本宫', '一世', '二世', '三世', '四世', '五世', '游魂', '归魂',
];

/** Walk the 64 entries and group them by their shared (defining) trigram.
 *  Returns a parallel array of length 64 where each element is the
 *  shared trigram of the entry's group — i.e. the palace's trigram. */
function derivePalaceTrigramPerEntry(): Trigram[] {
  const out: Trigram[] = new Array(RAW_DATA.length);
  let i = 0;
  while (i < RAW_DATA.length) {
    const head = RAW_DATA[i]!;
    if (head.shangGua !== head.xiaGua) {
      throw new Error(`hexagramData: entry[${i}] (${head.fullName}) is not a pure-trigram 本宫卦 — data file ordering is broken`);
    }
    const sharedTrigram = head.shangGua;
    // Group of 8 entries; first is 本宫, rest 1-7 (一世…归魂).
    for (let k = 0; k < 8; k++) {
      if (i + k >= RAW_DATA.length) {
        throw new Error(`hexagramData: incomplete 宫 group starting at index ${i} (trigram=${sharedTrigram})`);
      }
      out[i + k] = sharedTrigram;
    }
    i += 8;
  }
  return out;
}

const PALACE_TRIGRAM_PER_ENTRY = derivePalaceTrigramPerEntry();

/** Map data file `code` to engine bits.
 *
 *  The data file encodes each line as one of:
 *    0 = 阴 (少阴 8)
 *    1 = 阳 (少阳 7) — STATIC
 *    2 = 阳 (老阳 9) — MOVING
 *
 *  The engine's hexagramSkill, however, normalizes the raw 6/7/8/9
 *  yao value to a 1-bit yin/yang flag (0/1) via `yaoToBit`, so the
 *  engine's HEXAGRAMS_BY_BITS key is the bit-array (1=阳 0=阴)
 *  produced from a STATIC hexagram (i.e. one without 老阳 lines).
 *
 *  For a static hexagram the data file's `code` is identical to the
 *  engine key (digit 0 → bit 0, digit 1 → bit 1, no 2s). For a
 *  hexagram WITH moving lines (any 2 in the data code), the static
 *  version is the same as the changed version after 9→6 flips, so
 *  the static key is what we want.
 *
 *  We only cross-check the data file's code against the trigram pair
 *  when the code contains no 2s (no moving lines). If it does, the
 *  cross-check is skipped (the code is for the original-cast view,
 *  not the static view).
 */
function dataCodeToStaticBits(code: string): string {
  if (!/^[0-2]{6}$/.test(code)) {
    throw new Error(`hexagramData: bad code "${code}" — expected 6 digits of 0/1/2`);
  }
  return code.split('').map((c) => (c === '0' ? '0' : '1')).join('');
}

/** Build the runtime lookup tables. */
function buildTables(): {
  byId: Record<number, HexagramMeta>;
  byName: Record<string, HexagramMeta>;
  byBits: Record<string, HexagramMeta>;
} {
  const byId: Record<number, HexagramMeta> = {};
  const byName: Record<string, HexagramMeta> = {};
  const byBits: Record<string, HexagramMeta> = {};
  for (let i = 0; i < RAW_DATA.length; i++) {
    const r = RAW_DATA[i]!;
    const palaceTrigram = PALACE_TRIGRAM_PER_ENTRY[i]!;
    const palace: Palace = PALACE_OF_TRIGRAM[palaceTrigram];
    const element: WuXing = TRIGRAM_ELEMENT[palaceTrigram];
    const palaceType = PALACE_TYPE_BY_INDEX[i % 8]!;
    const id = i + 1;
    const meta: HexagramMeta = {
      id,
      name: r.name,
      upper: r.shangGua,
      lower: r.xiaGua,
      palace: palaceTrigram,
      palaceType,
      element,
    };
    byId[id] = meta;
    byName[r.name] = meta;
    // Use the engine-canonical bits (1/0, derived from the trigram
    // pair) so the key matches what hexagramSkill produces. This is
    // also more robust than mapping the data file's 2→1, because it
    // cross-checks that the (upper, lower) pair and the code field
    // agree.
    byBits[bitsFromTrigrams(r.shangGua, r.xiaGua)] = meta;
    // Sanity check: if the data file's code has no 老阳 (no 2s), it
    // should match the trigram-derived key exactly.
    if (!r.code.includes('2')) {
      const expected = dataCodeToStaticBits(r.code);
      const actual = bitsFromTrigrams(r.shangGua, r.xiaGua);
      if (expected !== actual) {
        throw new Error(
          `hexagramData: ${r.fullName} code mismatch — ` +
          `data file says ${r.code} (static bits ${expected}), ` +
          `trigram pair (${r.shangGua}/${r.xiaGua}) gives engine bits ${actual}`,
        );
      }
    }
  }
  return { byId, byName, byBits };
}

const TABLES = buildTables();

/** Lookup by 1..64 文王 ordering. */
export const HEXAGRAMS: Record<number, HexagramMeta> = TABLES.byId;

/** Lookup by 卦名 (short form, e.g. "乾" or "否"). */
export const HEXAGRAMS_BY_NAME: Record<string, HexagramMeta> = TABLES.byName;

/** Lookup by 6-bit engine string (bottom-to-top, 1=阳 0=阴). */
export const HEXAGRAMS_BY_BITS: Record<string, HexagramMeta> = TABLES.byBits;

/** Re-export the raw 64-卦 JSON for tools that need 卦辞/爻辞 (the
 *  analysis agent pulls these for the report template). */
export const HEXAGRAM_RAW_DATA: readonly RawHexagram[] = RAW_DATA;

/** Internal helper: per-entry palace trigram (length 64). Useful for
 *  tests; not part of the public API. */
export const _PALACE_TRIGRAM_PER_ENTRY: readonly Trigram[] = PALACE_TRIGRAM_PER_ENTRY;
